.TH "TXT2REGEX" 1 "September, 28th - 2004" ""

.SH NAME
.P
txt2regex \- the console Regular Expression Wizard
.SH SYNOPSIS
.P
\fBtxt2regex\fR [ \-\-nocolor | \-\-whitebg ] [ \-\-all | \-\-prog PROGRAMS ]
.P
\fBtxt2regex\fR \-\-showmeta
.P
\fBtxt2regex\fR \-\-showinfo PROGRAM [ \-\-nocolor ]
.P
\fBtxt2regex\fR \-\-history VALUE [ \-\-all | \-\-prog PROGRAMS ]
.P
\fBtxt2regex\fR \-\-make LABEL [ \-\-all | \-\-prog PROGRAMS ]
.SH DESCRIPTION
.P
\fBtxt2regex\fR is a Regular Expression Wizard that converts human
sentences to regexes.
.P
In a simple interactive console interface, the user answer questions
and the program build the regexes for more than 20 programs, like Vim,
Emacs, Perl, PHP, Python, Procmail and OpenOffice.org.
.P
It is a Shell Script 100% written with Bash builtin commands. No
compilation or extra commands are needed, just download and run.
.P
Please visit the program homepage at
\fIhttps://aurelio.net/projects/txt2regex/\fR.
.SH OPTIONS

.TP
\fB\-\-all\fR
Works with all registered programs

.TP
\fB\-\-help\fR
Prints the help message and quit

.TP
\fB\-\-history <value>\fR
Prints to STDOUT a regex from a history data

.TP
\fB\-\-make <target>\fR
Prints a ready regex for a common pattern

.TP
\fB\-\-nocolor\fR
Self\-explanatory

.TP
\fB\-\-prog <p1,p2,...>\fR
Choose which programs to use (separated by commas)

.TP
\fB\-\-showinfo <program>\fR
Prints regex info about the program

.TP
\fB\-\-showmeta\fR
Prints a complete metachar table for all programs

.TP
\fB\-\-version\fR
Prints the program version and quit

.TP
\fB\-\-whitebg\fR
Colors adjusted to white background terminals

.P
By default, all options are turned OFF. Just call it with no options
to launch the default interactive interface.
.SH DETAILS
.P
\fB\-\-all\fR is cool but requires lots of lines (~35)
.P
\fB\-\-nocolor\fR is strong, so it kills \-\-whitebg
.P
\fB\-\-showmeta\fR rules, try it
.P
\fB\-\-showinfo\fR uses reverse video output, \-\-nocolor turns it off
.P
\fB\-\-history\fR is getting useful, stay tunned
.P
\fB\-\-make\fR is a remedy for headaches
.P
\fB\-\-prog\fR is nice to use your favorite programs, mix it with \-\-make and \-\-history
.SH EXAMPLES

.TP
Calling the program on the default interactive interface

.nf
$ txt2regex
.fi



.TP
Calling the program on a white terminal

.nf
$ xterm -fg black -bg white ; txt2regex --whitebg
.fi



.TP
Getting information

.nf
$ txt2regex --showmeta
.fi



.TP
Getting specific information

.nf
$ txt2regex --showinfo sed
.fi



.TP
Calling it for specific programs

.nf
$ txt2regex --prog vim,sed,grep,python
.fi



.TP
Applying a history data

.nf
$ txt2regex --history '16421¤:01¤:'
.fi



.TP
Getting ready regexes!

.nf
$ txt2regex --make hour
$ txt2regex --make number3 --prog perl
$ txt2regex --make date2 --all
.fi



.SH INTERFACE
.P
The program interface is simple and easy to use. This is its contents:

.nf
    +---------------------------------------+
    | -> Top menu                           |
    | -> Group menu                         |
    |                                       |
    | -> Regexes of the programs selected   |
    |    ...                                |
    |    ...                                |
    |                                       |
    | -> History                            |
    | -> Your prompt                        |
    |                                       |
    | -> The question                       |
    | -> The answers                        |
    |    ...                                |
    |    ...                                |
    +---------------------------------------+
.fi


.P
All the basic commands can be used on the numeric pad on the keyboard,
but remember to turn ON the NumLock key.

.TS
center, tab(^); cl.
 \fBCommand\fR^\fBDescription\fR
 \fB.\fR^Quit the program (with confirmation)
 \fB0\fR^Reset the Regular Expression
 \fB1\-9\fR^Answers the questions
 \fB*\fR^Toggles color ON/OFF
 \fB/\fR^Add/remove programs on/from the list
 \fB|\fR^Insert an alternation (where allowed)
 \fB(\fR^Open a new group (where allowed)
 \fB)\fR^Close the opened group (if any)
.TE

.SH BUGS
.P
Bug reports and contributions are VERY welcome!
Please use the GitHub issues system:
https://github.com/aureliojargas/txt2regex/issues
.SH AUTHOR
.P
Written and maintained by Aurelio Jargas <verde@aurelio.net>
.SH COPYRIGHT
.P
Copyright © 2000\-2020 Aurelio Jargas
.P
This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

.\" man code generated by txt2tags 3.4 (http://txt2tags.org)
.\" cmdline: txt2tags -t man man/txt2regex.t2t
