#!/bin/bash
# bashdump-rmdup.sh
# Remove the duplicated entries from a potfile generated by the
# command: bash --dump-po-strings
# 20010609 <verde@aurelio.net> ** debut

[ "$1" ] || {
    echo "usage: $0 potfile"
    exit 1
}

potfile="$1"
tmp="$potfile".tmp
sedscript="$potfile".sed

# Extract all msgid messages from the potfile, with their line numbers
# appended. Sample output:
#   letters#156
#   lowercase letters#141
#   lowercase letters#159
#   metas#222
#   need esc#228
cat -n "$potfile" |
  sed -n 's/^[[:blank:]]*\([0-9][0-9]*\)[[:blank:]]*msgid "\(..*\)"$/\2#\1/p' |
  sort > "$tmp"

duplicates=$(sed 's/#[0-9][0-9]*$//' "$tmp" | uniq -d)

test -z "$duplicates" && {
    echo "No duplicate messages found. Nothing to do."
    exit 0
}

echo "$duplicates" |
while read -r message
do
    echo "Duplicated message found: $message"

    # Get the original line number for all the duplicated messages.
    # Note that the first occurrence is excluded from that list, so it
    # won't be removed in the next loop.
    dup_lines=$(
        sed -n "s/^$message#\\([0-9]*\\)$/\\1/p" "$tmp" |
            sort -n |
            sed 1d
    )

    # Compose the sed command to remove the entry. The msgid and msgstr
    # lines are removed and the comment line is changed. For example:
    #
    #     #: txt2regex.sh:348
    #     msgid "lowercase letters"
    #     msgstr ""
    #
    # becomes:
    #
    #     ##duplicated##: txt2regex.sh:348
    #
    # Note that sed remembers the original line numbers, so removing
    # lines at the top won't affect the removal of lines at the bottom.
    for line in $dup_lines
    do
        before=$((line - 1))
        after=$((line + 1))
        printf '%d s/^#/##duplicated##/; %d d; %d d\n' \
            "$before" "$line" "$after" >> "$sedscript"
    done
done

echo
echo "sed script that will be applied:"
cat "$sedscript"

# Edit the potfile in-place (in a portable way)
cp "$potfile" "$tmp"
sed -f "$sedscript" "$tmp" > "$potfile"

rm "$tmp" "$sedscript"

echo
echo "OK, $potfile was rewritten. No more dups! \\o/"
