# https://docs.github.com/en/actions/reference

name: Check
on: push
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Actions runner ignores SIGPIPE
        run: |
          set -o | grep -e pipefail -e errexit
          trap
          yes | head -n 1
        shell: bash --noprofile --norc -e -x {0}

      - name: Using Python to run commands, SIGPIPE is not ignored
        run: python3 -c 'import subprocess as s; s.run(["trap; yes | head -n 1"], shell=True)'

      - name: Using Python as the shell to run shell commands
        run: |
          trap
          yes | head -n 1
        shell: |
          python3 -c 'import subprocess as s; with open("{0}") as f: s.run([f.read()], shell=True)'

        # Not supported in Ubuntu 20.04
        #shell: env --default-signal=PIPE bash --noprofile --norc -e {0}
