# https://docs.github.com/en/actions/reference

name: Check
on:
  push:
  pull_request:
jobs:

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo snap install shfmt
      - run: make lint

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      # See https://github.com/aureliojargas/txt2regex/pull/9 on why we're
      # using env in the next command
      - run: env --default-signal=PIPE make test
      - run: make test-bash
      - run: make test-regex

      - name: The repository must remain unchanged after the checks
        run: |
          git diff
          git diff-index --exit-code HEAD
