# https://docs.github.com/en/actions/reference

name: Check
on: push
jobs:

  clitest:
    runs-on: ubuntu-latest
    container:
      image: aureliojargas/clitest
      volumes:
        - /home/runner/work/txt2regex/txt2regex:/mnt
    steps:
      - run: clitest --help
      - run: |
          cd /mnt; ls -la; mount
          clitest --progress none README.md tests/*.md

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      # /home/runner/work/txt2regex/txt2regex

      - name: GitHub Actions runner ignores SIGPIPE
        run: |
          set -o | grep -e pipefail -e errexit
          trap
          yes | head -n 1
        shell: bash --noprofile --norc -e -x {0}

      - name: Using Python to run commands, SIGPIPE is not ignored
        run: python3 -c 'import subprocess as s; s.run(["trap; yes | head -n 1"], shell=True)'

      - name: Using Python as the shell to run shell commands - cmd=
        run: |
          cmd = "trap; yes | head -n 1"
          import subprocess as s; s.run([cmd], shell=True)
        shell: python

      - name: Using Python as the shell to run shell commands - env
        env:
          CMD: "trap; yes | head -n 1"
        run: |
          import os, subprocess as s; s.run([os.environ["CMD"]], shell=True)
        shell: python

      - name: Using Python as the shell to run shell commands - 3
        run: "trap; yes | head -n 1"
        shell: |
          python3 -c 'import subprocess as s; with open("{0}") as f: s.run([f.read()], shell=True)'

        # Not supported in Ubuntu 20.04
        #shell: env --default-signal=PIPE bash --noprofile --norc -e {0}
